### ISSUE TITLE
The command line is too long.

### ISSUE THREAD

**Issue by TeamPopplio** [YTP-Plus/YTPPlusCLI#2]
This error occurs when you use a lot of clips (tried 200 clips to replicate).
Suggested fix: Test for command length before rendering video.

**Comment by TeamPopplio** [comment]
Fixed using 322f90b2137cdad27fdbe06a9f7bbacfd2a7ebcc's concat method.

**Comment by DevanWolf** [comment]
The optimized code from #4 too solves that problem.
